#!/usr/bin/env bash
#This Script creates a file /var/run/myscript.pid containing its PID
#Run indefinitely displaying "To infinity and beyond"
#Handles multiples signals such as SIGTERM, SIGINT and SIGQUIT


sh -c 'echo $$ > /var/run/myscript.pid'
trap 'echo "I hate the kill command";sudo rm /var/run/myscript.pid;exit 0' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm /var/run/myscript.pid;exit 0' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done