#!/usr/bin/env bash
#The Script Prints "Hello School" 10 times, and "Hi" on the 9th iteration.

((i = 1))

while true; do
    echo "Best School"
    if ((i == 9)); then
        echo "Hi"
    fi
    if ((i == 10)); then
        break
    fi
    ((i++))
done