#!/usr/bin/env bash
#This Script displays the content of the current directory
#in a list format
#display only the part of the name after the first dash is displayed

current_directory=$(ls)

for file in $current_directory; do
    echo "$file" | cut -d "-" -f2-
done